-- No-op migration.
--
-- An earlier version of this file contained Prisma drift renames (truncated
-- PostgreSQL index/constraint names). Those renames are invalid on a clean
-- migration replay because:
--   1. Several indexes belong to project-learning tables created in later
--      migrations (20260805120000_project_learning_foundation and after).
--   2. Source names referenced truncated identifiers that were never created
--      by prior migration SQL.
--
-- Later migrations already create the correct final index/constraint names.
