-- RP-04.2B: account evidence eligibility. Exact-email backfill from seed definitions only.
-- Operator ELIGIBLE allowlist is empty by default (fail-closed for unknown accounts).

CREATE TYPE "RecommendationEvidenceEligibility" AS ENUM (
  'UNCLASSIFIED',
  'ELIGIBLE',
  'EXCLUDED_DEMO',
  'EXCLUDED_TEST',
  'EXCLUDED_INTERNAL'
);

ALTER TABLE "users"
ADD COLUMN "recommendation_evidence_eligibility" "RecommendationEvidenceEligibility";

UPDATE "users"
SET "recommendation_evidence_eligibility" = 'UNCLASSIFIED'
WHERE "recommendation_evidence_eligibility" IS NULL;

UPDATE "users"
SET "recommendation_evidence_eligibility" = 'EXCLUDED_DEMO'
WHERE lower("email") IN (
  'majd@learner.com',
  'israa@learner.com',
  'learner@learner.com',
  'seed-learner-ahmad@impactloop.test',
  'seed-learner-sara@impactloop.test',
  'seed-learner-omar@impactloop.test',
  'seed-learner-lina@impactloop.test',
  'seed-learner-yousef@impactloop.test',
  'majd@supplier.com',
  'israa@supplier.com',
  'supplier@supplier.com',
  'seed-supplier@impactloop.test',
  'workshop.verify.pending@impactloop.test',
  'factory.verify.pending@impactloop.test',
  'university.verify.approved@impactloop.test',
  'workshop.verify.changes@impactloop.test',
  'ahmad.khalil@community.impactloop.test',
  'ahmad.nasser@community.impactloop.test',
  'ahmad.saleh@community.impactloop.test',
  'ahmad.haddad@community.impactloop.test',
  'ahmad.qasem@community.impactloop.test',
  'ahmad.darwish@community.impactloop.test',
  'ahmad.mansour@community.impactloop.test',
  'ahmad.barakat@community.impactloop.test',
  'ahmad.awad@community.impactloop.test',
  'ahmad.hamdan@community.impactloop.test',
  'ahmad.jaber@community.impactloop.test',
  'ahmad.shami@community.impactloop.test',
  'mohammad.khalil@community.impactloop.test',
  'mohammad.nasser@community.impactloop.test',
  'mohammad.saleh@community.impactloop.test',
  'mohammad.haddad@community.impactloop.test',
  'mohammad.qasem@community.impactloop.test',
  'mohammad.darwish@community.impactloop.test',
  'mohammad.mansour@community.impactloop.test',
  'mohammad.barakat@community.impactloop.test',
  'mohammad.awad@community.impactloop.test',
  'mohammad.hamdan@community.impactloop.test',
  'mohammad.jaber@community.impactloop.test',
  'mohammad.shami@community.impactloop.test',
  'omar.khalil@community.impactloop.test',
  'omar.nasser@community.impactloop.test',
  'omar.saleh@community.impactloop.test',
  'omar.haddad@community.impactloop.test',
  'omar.qasem@community.impactloop.test',
  'omar.darwish@community.impactloop.test',
  'omar.mansour@community.impactloop.test',
  'omar.barakat@community.impactloop.test',
  'omar.awad@community.impactloop.test',
  'omar.hamdan@community.impactloop.test',
  'omar.jaber@community.impactloop.test',
  'omar.shami@community.impactloop.test',
  'yousef.khalil@community.impactloop.test',
  'yousef.nasser@community.impactloop.test',
  'yousef.saleh@community.impactloop.test',
  'yousef.haddad@community.impactloop.test',
  'yousef.qasem@community.impactloop.test',
  'yousef.darwish@community.impactloop.test',
  'yousef.mansour@community.impactloop.test',
  'yousef.barakat@community.impactloop.test',
  'yousef.awad@community.impactloop.test',
  'yousef.hamdan@community.impactloop.test',
  'yousef.jaber@community.impactloop.test',
  'yousef.shami@community.impactloop.test',
  'khaled.khalil@community.impactloop.test',
  'khaled.nasser@community.impactloop.test',
  'khaled.saleh@community.impactloop.test',
  'khaled.haddad@community.impactloop.test',
  'khaled.qasem@community.impactloop.test',
  'khaled.darwish@community.impactloop.test',
  'khaled.mansour@community.impactloop.test',
  'khaled.barakat@community.impactloop.test',
  'khaled.awad@community.impactloop.test',
  'khaled.hamdan@community.impactloop.test',
  'khaled.jaber@community.impactloop.test',
  'khaled.shami@community.impactloop.test',
  'laith.khalil@community.impactloop.test',
  'laith.nasser@community.impactloop.test',
  'laith.saleh@community.impactloop.test',
  'laith.haddad@community.impactloop.test',
  'laith.qasem@community.impactloop.test',
  'laith.darwish@community.impactloop.test',
  'laith.mansour@community.impactloop.test',
  'laith.barakat@community.impactloop.test',
  'laith.awad@community.impactloop.test',
  'laith.hamdan@community.impactloop.test',
  'laith.jaber@community.impactloop.test',
  'laith.shami@community.impactloop.test',
  'zaid.khalil@community.impactloop.test',
  'zaid.nasser@community.impactloop.test',
  'zaid.saleh@community.impactloop.test',
  'zaid.haddad@community.impactloop.test',
  'zaid.qasem@community.impactloop.test',
  'zaid.darwish@community.impactloop.test',
  'zaid.mansour@community.impactloop.test',
  'zaid.barakat@community.impactloop.test',
  'zaid.awad@community.impactloop.test',
  'zaid.hamdan@community.impactloop.test',
  'zaid.jaber@community.impactloop.test',
  'zaid.shami@community.impactloop.test',
  'hamza.khalil@community.impactloop.test',
  'hamza.nasser@community.impactloop.test',
  'hamza.saleh@community.impactloop.test',
  'hamza.haddad@community.impactloop.test',
  'hamza.qasem@community.impactloop.test',
  'hamza.darwish@community.impactloop.test',
  'hamza.mansour@community.impactloop.test',
  'hamza.barakat@community.impactloop.test',
  'hamza.awad@community.impactloop.test',
  'hamza.hamdan@community.impactloop.test',
  'hamza.jaber@community.impactloop.test',
  'hamza.shami@community.impactloop.test',
  'tariq.khalil@community.impactloop.test',
  'tariq.nasser@community.impactloop.test',
  'tariq.saleh@community.impactloop.test',
  'tariq.haddad@community.impactloop.test',
  'tariq.qasem@community.impactloop.test',
  'tariq.darwish@community.impactloop.test',
  'tariq.mansour@community.impactloop.test',
  'tariq.barakat@community.impactloop.test',
  'tariq.awad@community.impactloop.test',
  'tariq.hamdan@community.impactloop.test',
  'tariq.jaber@community.impactloop.test',
  'tariq.shami@community.impactloop.test',
  'samer.khalil@community.impactloop.test',
  'samer.nasser@community.impactloop.test',
  'samer.saleh@community.impactloop.test',
  'samer.haddad@community.impactloop.test',
  'samer.qasem@community.impactloop.test',
  'samer.darwish@community.impactloop.test',
  'samer.mansour@community.impactloop.test',
  'samer.barakat@community.impactloop.test',
  'samer.awad@community.impactloop.test',
  'samer.hamdan@community.impactloop.test',
  'samer.jaber@community.impactloop.test',
  'samer.shami@community.impactloop.test',
  'rami.khalil@community.impactloop.test',
  'rami.nasser@community.impactloop.test',
  'rami.saleh@community.impactloop.test',
  'rami.haddad@community.impactloop.test',
  'rami.qasem@community.impactloop.test',
  'rami.darwish@community.impactloop.test',
  'rami.mansour@community.impactloop.test',
  'rami.barakat@community.impactloop.test',
  'rami.awad@community.impactloop.test',
  'rami.hamdan@community.impactloop.test',
  'rami.jaber@community.impactloop.test',
  'rami.shami@community.impactloop.test',
  'anas.khalil@community.impactloop.test',
  'anas.nasser@community.impactloop.test',
  'anas.saleh@community.impactloop.test',
  'anas.haddad@community.impactloop.test',
  'anas.qasem@community.impactloop.test',
  'anas.darwish@community.impactloop.test',
  'anas.mansour@community.impactloop.test',
  'anas.barakat@community.impactloop.test',
  'anas.awad@community.impactloop.test',
  'anas.hamdan@community.impactloop.test',
  'anas.jaber@community.impactloop.test',
  'anas.shami@community.impactloop.test',
  'lina.khalil@community.impactloop.test',
  'lina.nasser@community.impactloop.test',
  'lina.saleh@community.impactloop.test',
  'lina.haddad@community.impactloop.test',
  'lina.qasem@community.impactloop.test',
  'lina.darwish@community.impactloop.test',
  'lina.mansour@community.impactloop.test',
  'lina.barakat@community.impactloop.test',
  'lina.awad@community.impactloop.test',
  'lina.hamdan@community.impactloop.test',
  'lina.jaber@community.impactloop.test',
  'lina.shami@community.impactloop.test',
  'sara.khalil@community.impactloop.test',
  'sara.nasser@community.impactloop.test',
  'sara.saleh@community.impactloop.test',
  'sara.haddad@community.impactloop.test',
  'sara.qasem@community.impactloop.test',
  'sara.darwish@community.impactloop.test',
  'sara.mansour@community.impactloop.test',
  'sara.barakat@community.impactloop.test',
  'sara.awad@community.impactloop.test',
  'sara.hamdan@community.impactloop.test',
  'sara.jaber@community.impactloop.test',
  'sara.shami@community.impactloop.test',
  'noor.khalil@community.impactloop.test',
  'noor.nasser@community.impactloop.test',
  'noor.saleh@community.impactloop.test',
  'noor.haddad@community.impactloop.test',
  'noor.qasem@community.impactloop.test',
  'noor.darwish@community.impactloop.test',
  'noor.mansour@community.impactloop.test',
  'noor.barakat@community.impactloop.test',
  'noor.awad@community.impactloop.test',
  'noor.hamdan@community.impactloop.test',
  'noor.jaber@community.impactloop.test',
  'noor.shami@community.impactloop.test',
  'dana.khalil@community.impactloop.test',
  'dana.nasser@community.impactloop.test',
  'dana.saleh@community.impactloop.test',
  'dana.haddad@community.impactloop.test',
  'dana.qasem@community.impactloop.test',
  'dana.darwish@community.impactloop.test',
  'dana.mansour@community.impactloop.test',
  'dana.barakat@community.impactloop.test',
  'dana.awad@community.impactloop.test',
  'dana.hamdan@community.impactloop.test',
  'dana.jaber@community.impactloop.test',
  'dana.shami@community.impactloop.test',
  'hala.khalil@community.impactloop.test',
  'hala.nasser@community.impactloop.test',
  'hala.saleh@community.impactloop.test',
  'hala.haddad@community.impactloop.test',
  'hala.qasem@community.impactloop.test',
  'hala.darwish@community.impactloop.test',
  'hala.mansour@community.impactloop.test',
  'hala.barakat@community.impactloop.test',
  'hala.awad@community.impactloop.test',
  'hala.hamdan@community.impactloop.test',
  'hala.jaber@community.impactloop.test',
  'hala.shami@community.impactloop.test',
  'aya.khalil@community.impactloop.test',
  'aya.nasser@community.impactloop.test',
  'aya.saleh@community.impactloop.test',
  'aya.haddad@community.impactloop.test',
  'aya.qasem@community.impactloop.test',
  'aya.darwish@community.impactloop.test',
  'aya.mansour@community.impactloop.test',
  'aya.barakat@community.impactloop.test',
  'aya.awad@community.impactloop.test',
  'aya.hamdan@community.impactloop.test',
  'aya.jaber@community.impactloop.test',
  'aya.shami@community.impactloop.test',
  'rana.khalil@community.impactloop.test',
  'rana.nasser@community.impactloop.test',
  'rana.saleh@community.impactloop.test',
  'rana.haddad@community.impactloop.test',
  'rana.qasem@community.impactloop.test',
  'rana.darwish@community.impactloop.test',
  'rana.mansour@community.impactloop.test',
  'rana.barakat@community.impactloop.test',
  'rana.awad@community.impactloop.test',
  'rana.hamdan@community.impactloop.test',
  'rana.jaber@community.impactloop.test',
  'rana.shami@community.impactloop.test',
  'maya.khalil@community.impactloop.test',
  'maya.nasser@community.impactloop.test',
  'maya.saleh@community.impactloop.test',
  'maya.haddad@community.impactloop.test',
  'maya.qasem@community.impactloop.test',
  'maya.darwish@community.impactloop.test',
  'maya.mansour@community.impactloop.test',
  'maya.barakat@community.impactloop.test',
  'maya.awad@community.impactloop.test',
  'maya.hamdan@community.impactloop.test',
  'maya.jaber@community.impactloop.test',
  'maya.shami@community.impactloop.test',
  'salma.khalil@community.impactloop.test',
  'salma.nasser@community.impactloop.test',
  'salma.saleh@community.impactloop.test',
  'salma.haddad@community.impactloop.test',
  'salma.qasem@community.impactloop.test',
  'salma.darwish@community.impactloop.test',
  'salma.mansour@community.impactloop.test',
  'salma.barakat@community.impactloop.test',
  'salma.awad@community.impactloop.test',
  'salma.hamdan@community.impactloop.test',
  'salma.jaber@community.impactloop.test',
  'salma.shami@community.impactloop.test',
  'dina.khalil@community.impactloop.test',
  'dina.nasser@community.impactloop.test',
  'dina.saleh@community.impactloop.test',
  'dina.haddad@community.impactloop.test',
  'dina.qasem@community.impactloop.test',
  'dina.darwish@community.impactloop.test',
  'dina.mansour@community.impactloop.test',
  'dina.barakat@community.impactloop.test',
  'dina.awad@community.impactloop.test',
  'dina.hamdan@community.impactloop.test',
  'dina.jaber@community.impactloop.test',
  'dina.shami@community.impactloop.test',
  'reem.khalil@community.impactloop.test',
  'reem.nasser@community.impactloop.test',
  'reem.saleh@community.impactloop.test',
  'reem.haddad@community.impactloop.test',
  'reem.qasem@community.impactloop.test',
  'reem.darwish@community.impactloop.test',
  'reem.mansour@community.impactloop.test',
  'reem.barakat@community.impactloop.test',
  'reem.awad@community.impactloop.test',
  'reem.hamdan@community.impactloop.test',
  'reem.jaber@community.impactloop.test',
  'reem.shami@community.impactloop.test',
  'nour.khalil@community.impactloop.test',
  'nour.nasser@community.impactloop.test',
  'nour.saleh@community.impactloop.test',
  'nour.haddad@community.impactloop.test',
  'nour.qasem@community.impactloop.test',
  'nour.darwish@community.impactloop.test',
  'nour.mansour@community.impactloop.test',
  'nour.barakat@community.impactloop.test',
  'nour.awad@community.impactloop.test',
  'nour.hamdan@community.impactloop.test',
  'nour.jaber@community.impactloop.test',
  'nour.shami@community.impactloop.test'
);

UPDATE "users"
SET "recommendation_evidence_eligibility" = 'EXCLUDED_INTERNAL'
WHERE lower("email") IN (
  'majd@admin.com',
  'israa@admin.com',
  'admin@admin.com',
  'admin@impactloop.test',
  'majd@driver.com',
  'israa@driver.com',
  'driver@driver.com'
);

-- Operator-supplied ELIGIBLE allowlist (exact emails).
-- Insert emails between the markers and uncomment the UPDATE to promote accounts.
-- RP_04_2_ELIGIBLE_ALLOWLIST_START
-- UPDATE "users"
-- SET "recommendation_evidence_eligibility" = 'ELIGIBLE'
-- WHERE lower("email") IN (
--   'legitimate.user@example.com'
-- );
-- RP_04_2_ELIGIBLE_ALLOWLIST_END

ALTER TABLE "users"
ALTER COLUMN "recommendation_evidence_eligibility" SET DEFAULT 'ELIGIBLE';

ALTER TABLE "users"
ALTER COLUMN "recommendation_evidence_eligibility" SET NOT NULL;
