export const DRIVER_NOTIFICATION_TYPES = {
  DRIVER_NEW_JOB: 'DRIVER_NEW_JOB',
  DRIVER_PICKUP_TIME: 'DRIVER_PICKUP_TIME',
  DRIVER_DROPOFF_TIME: 'DRIVER_DROPOFF_TIME',
  DRIVER_DELIVERY_UNASSIGNED_BY_ADMIN: 'DRIVER_DELIVERY_UNASSIGNED_BY_ADMIN',
  DRIVER_DELIVERY_MOVED_TO_ADMIN_REVIEW: 'DRIVER_DELIVERY_MOVED_TO_ADMIN_REVIEW',
  DRIVER_DELIVERY_RETURN_REQUIRED: 'DRIVER_DELIVERY_RETURN_REQUIRED',
  DRIVER_DELIVERY_RETURN_CONFIRMED: 'DRIVER_DELIVERY_RETURN_CONFIRMED',
} as const;

/** Only these driver notification types may be created or shown. */
export const ALLOWED_DRIVER_NOTIFICATION_TYPES = [
  DRIVER_NOTIFICATION_TYPES.DRIVER_NEW_JOB,
  DRIVER_NOTIFICATION_TYPES.DRIVER_PICKUP_TIME,
  DRIVER_NOTIFICATION_TYPES.DRIVER_DROPOFF_TIME,
  DRIVER_NOTIFICATION_TYPES.DRIVER_DELIVERY_UNASSIGNED_BY_ADMIN,
  DRIVER_NOTIFICATION_TYPES.DRIVER_DELIVERY_MOVED_TO_ADMIN_REVIEW,
  DRIVER_NOTIFICATION_TYPES.DRIVER_DELIVERY_RETURN_REQUIRED,
  DRIVER_NOTIFICATION_TYPES.DRIVER_DELIVERY_RETURN_CONFIRMED,
] as const;

/** Legacy types hidden from driver inbox (never created). */
export const LEGACY_DRIVER_NOTIFICATION_TYPES = [
  'DRIVER_DELIVERY_AVAILABLE',
  'DRIVER_DELIVERY_REQUEST_CREATED',
  'DRIVER_PICKUP_REMINDER',
  'DRIVER_DROPOFF_REMINDER',
  'DRIVER_PICKUP_STARTING_SOON',
  'DRIVER_DROPOFF_STARTING_SOON',
  'DRIVER_PICKUP_WINDOW_STARTED',
  'DRIVER_PICKUP_OVERDUE',
  'DRIVER_DROPOFF_WINDOW_STARTED',
  'DRIVER_DROPOFF_OVERDUE',
  'DRIVER_DELIVERY_ACCEPTED',
  'DRIVER_DELIVERY_NEXT_STEP',
] as const;

export type DriverNotificationType =
  (typeof DRIVER_NOTIFICATION_TYPES)[keyof typeof DRIVER_NOTIFICATION_TYPES];

export const isAllowedDriverNotificationType = (notificationType: string) =>
  (ALLOWED_DRIVER_NOTIFICATION_TYPES as readonly string[]).includes(
    notificationType,
  );

export const isDriverDeliveryNotificationType = (notificationType: string) =>
  notificationType.startsWith('DRIVER_');

/** @deprecated Use DRIVER_NOTIFICATION_TYPES */
export const DRIVER_DELIVERY_NOTIFICATION_TYPES = {
  ...DRIVER_NOTIFICATION_TYPES,
  DRIVER_DELIVERY_AVAILABLE: 'DRIVER_DELIVERY_AVAILABLE',
  DRIVER_DELIVERY_REQUEST_CREATED: 'DRIVER_DELIVERY_REQUEST_CREATED',
  DRIVER_PICKUP_REMINDER: 'DRIVER_PICKUP_REMINDER',
  DRIVER_DROPOFF_REMINDER: 'DRIVER_DROPOFF_REMINDER',
  DRIVER_PICKUP_STARTING_SOON: 'DRIVER_PICKUP_STARTING_SOON',
  DRIVER_DROPOFF_STARTING_SOON: 'DRIVER_DROPOFF_STARTING_SOON',
  DRIVER_PICKUP_WINDOW_STARTED: 'DRIVER_PICKUP_WINDOW_STARTED',
  DRIVER_PICKUP_OVERDUE: 'DRIVER_PICKUP_OVERDUE',
  DRIVER_DROPOFF_WINDOW_STARTED: 'DRIVER_DROPOFF_WINDOW_STARTED',
  DRIVER_DROPOFF_OVERDUE: 'DRIVER_DROPOFF_OVERDUE',
  DRIVER_DELIVERY_ACCEPTED: 'DRIVER_DELIVERY_ACCEPTED',
  DRIVER_DELIVERY_NEXT_STEP: 'DRIVER_DELIVERY_NEXT_STEP',
  DRIVER_DELIVERY_UNASSIGNED_BY_ADMIN:
    DRIVER_NOTIFICATION_TYPES.DRIVER_DELIVERY_UNASSIGNED_BY_ADMIN,
} as const;
