export const DRIVER_DELIVERY_NOTIFICATION_TYPES = {
  DRIVER_DELIVERY_AVAILABLE: 'DRIVER_DELIVERY_AVAILABLE',
  DRIVER_PICKUP_STARTING_SOON: 'DRIVER_PICKUP_STARTING_SOON',
  DRIVER_PICKUP_WINDOW_STARTED: 'DRIVER_PICKUP_WINDOW_STARTED',
  DRIVER_PICKUP_OVERDUE: 'DRIVER_PICKUP_OVERDUE',
  DRIVER_DROPOFF_STARTING_SOON: 'DRIVER_DROPOFF_STARTING_SOON',
  DRIVER_DROPOFF_WINDOW_STARTED: 'DRIVER_DROPOFF_WINDOW_STARTED',
  DRIVER_DROPOFF_OVERDUE: 'DRIVER_DROPOFF_OVERDUE',
  DRIVER_DELIVERY_ACCEPTED: 'DRIVER_DELIVERY_ACCEPTED',
  DRIVER_DELIVERY_NEXT_STEP: 'DRIVER_DELIVERY_NEXT_STEP',
  DRIVER_DELIVERY_MOVED_TO_ADMIN_REVIEW: 'DRIVER_DELIVERY_MOVED_TO_ADMIN_REVIEW',
} as const;

export type DriverDeliveryNotificationType =
  (typeof DRIVER_DELIVERY_NOTIFICATION_TYPES)[keyof typeof DRIVER_DELIVERY_NOTIFICATION_TYPES];
