// Closed vocabulary for navigation identifiers written to notification rows.
// Notification event types remain open so legacy and future events can still be read.
export const NOTIFICATION_ENTITY_TYPES = {
  RESERVATION: 'RESERVATION',
  DELIVERY: 'DELIVERY',
  MATERIAL: 'MATERIAL',
  MATERIAL_REQUEST: 'MATERIAL_REQUEST',
  CATEGORY_REQUEST: 'CATEGORY_REQUEST',
  PRICE_RULE_REQUEST: 'PRICE_RULE_REQUEST',
  SUPPLIER_PROFILE: 'SUPPLIER_PROFILE',
  LEARNING_PROJECT: 'LEARNING_PROJECT',
  PROJECT_HELP_SESSION: 'PROJECT_HELP_SESSION',
} as const;

export type NotificationEntityType =
  (typeof NOTIFICATION_ENTITY_TYPES)[keyof typeof NOTIFICATION_ENTITY_TYPES];

export const NOTIFICATION_ACTION_TYPES = {
  REVIEW_RESERVATION: 'REVIEW_RESERVATION',
  OPEN_RESERVATION: 'OPEN_RESERVATION',
  CHOOSE_PICKUP_WINDOW: 'CHOOSE_PICKUP_WINDOW',
  OPEN_MATERIAL: 'OPEN_MATERIAL',
  CONTINUE_LISTING: 'CONTINUE_LISTING',
  EDIT_LISTING: 'EDIT_LISTING',
  OPEN_PROFILE: 'OPEN_PROFILE',
  OPEN_ENTITY: 'OPEN_ENTITY',
  OPEN_LEARNING_PROJECT_SUBMISSION: 'OPEN_LEARNING_PROJECT_SUBMISSION',
  OPEN_PROJECT_HELP_SESSION: 'OPEN_PROJECT_HELP_SESSION',
  NONE: 'NONE',
} as const;

export type NotificationActionType =
  (typeof NOTIFICATION_ACTION_TYPES)[keyof typeof NOTIFICATION_ACTION_TYPES];
