/**
 * PROJECT-DATA-03 — curated An-Najah-inspired Arabic Learning Projects.
 * Single-language schema: Arabic prose in title/shortDescription/description/steps.
 * Technical model names remain mixed into Arabic where natural.
 *
 * SOURCE vs IMPACTLOOP ADAPTATION discipline is preserved in notes and comments.
 */

import { communityDemoProjectImageUrl } from '../../../src/constants/community-demo-projects.js';

export const DEMO_PROJECT_KEY_PREFIX = 'demo-project-key:';
export const PROJECT_DATA_03_BATCH_TAG = 'project-data-03';

export type ProjectData03Component = {
  name: string;
  materialType: string;
  categoryKey: string;
  quantity: number;
  unit: string;
  role: 'REQUIRED_MATERIAL' | 'OPTIONAL_MATERIAL' | 'TOOL' | 'CONSUMABLE';
  required: boolean;
  substitute: boolean;
  keywords: string[];
  alternatives?: string[];
  notes?: string;
  /** Existing taxonomy COMPONENT canonical key when safe. */
  conceptKey?: string;
};

export type ProjectData03Link = {
  linkType: 'ARTICLE' | 'PDF' | 'YOUTUBE' | 'GITHUB' | 'OTHER';
  url: string;
  title: string;
  sourceName: string;
};

export type ProjectData03Project = {
  key: string;
  authorEmail: string;
  title: string;
  shortDescription: string;
  description: string;
  categoryKey: string;
  difficulty: 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED';
  estimatedDurationMinutes: number;
  coverImageUrl: string;
  status: 'PUBLISHED' | 'PENDING_REVIEW';
  components: ProjectData03Component[];
  steps: Array<{ title: string; description: string }>;
  links: ProjectData03Link[];
  tags: string[];
};

/**
 * Local demo cover assets under prisma/demo-data/projects/source-images/covers/.
 * DB stores relative public URLs; clients resolve via API base (no localhost in rows).
 */
export const PROJECT_DATA_03_IMAGE_MANIFEST = [
  {
    key: 'najah-packsort-smart-package-sorter',
    coverFile: 'covers/najah-packsort-cover.png',
    coverImageUrl: communityDemoProjectImageUrl(
      'covers/najah-packsort-cover.png',
    ),
    status: 'local-demo-asset',
    note: 'Repository-owned PackSort cover for PROJECT-DATA-03.',
  },
  {
    key: 'najah-automated-liquid-sample-trainer',
    coverFile: 'covers/najah-sample-prep-cover.png',
    coverImageUrl: communityDemoProjectImageUrl(
      'covers/najah-sample-prep-cover.png',
    ),
    status: 'local-demo-asset',
    note: 'Repository-owned sample trainer cover for PROJECT-DATA-03.',
  },
  {
    key: 'najah-wireless-braille-printer',
    coverFile: 'covers/najah-braille-printer-cover.png',
    coverImageUrl: communityDemoProjectImageUrl(
      'covers/najah-braille-printer-cover.png',
    ),
    status: 'local-demo-asset',
    note: 'Repository-owned Braille printer cover for PROJECT-DATA-03.',
  },
  {
    key: 'najah-rootrise-cnc-plant-care',
    coverFile: 'covers/najah-rootrise-cover.png',
    coverImageUrl: communityDemoProjectImageUrl(
      'covers/najah-rootrise-cover.png',
    ),
    status: 'local-demo-asset',
    note: 'Repository-owned RootRise cover for PROJECT-DATA-03.',
  },
  {
    key: 'najah-henna-cnc-pattern-machine',
    coverFile: 'covers/najah-henna-cnc-cover.png',
    coverImageUrl: communityDemoProjectImageUrl(
      'covers/najah-henna-cnc-cover.png',
    ),
    status: 'local-demo-asset',
    note: 'Repository-owned Henna CNC cover for PROJECT-DATA-03.',
  },
  {
    key: 'najah-map-go-ros-lidar-robot',
    coverFile: 'covers/najah-map-go-cover.png',
    coverImageUrl: communityDemoProjectImageUrl(
      'covers/najah-map-go-cover.png',
    ),
    status: 'local-demo-asset',
    note: 'Repository-owned MAP&GO cover for PROJECT-DATA-03.',
  },
  {
    key: 'najah-bottle-separator-robot',
    coverFile: 'covers/najah-bottle-separator-cover.png',
    coverImageUrl: communityDemoProjectImageUrl(
      'covers/najah-bottle-separator-cover.png',
    ),
    status: 'local-demo-asset',
    note: 'Repository-owned bottle separator cover for PROJECT-DATA-03.',
  },
] as const;

const coverFor = (key: string) =>
  PROJECT_DATA_03_IMAGE_MANIFEST.find((entry) => entry.key === key)!.coverImageUrl;

export const PROJECT_DATA_03_PROJECTS: readonly ProjectData03Project[] = [
  {
    key: 'najah-packsort-smart-package-sorter',
    authorEmail: 'majd@learner.com',
    title: 'PackSort — نظام ذكي لفرز الطرود',
    shortDescription:
      'ابنِ نظام فرز آلي يستخدم Arduino وحزامًا ناقلًا لتمييز الطرود حسب الحجم واللون والـBarcode، ثم يدفع كل طرد إلى المسار المناسب باستخدام Servo Motors.',
    description:
      'في هذا المشروع ستبني نموذجًا تعليميًا لنظام فرز طرود مستوحى من أنظمة الأتمتة الصناعية (مستند إلى مشروع تخرج في جامعة النجاح). يجمع النظام بيانات من Ultrasonic وIR وColor Sensor وBarcode Scanner، ثم يستخدم Arduino Mega لاتخاذ قرار الفرز والتحكم بمحرك الحزام وServo pushers. يمكن إضافة ESP32 لعرض حالة النظام وإحصاءات الفرز لاسلكيًا. النسخة التعليمية لا تحتاج منشأة صناعية كاملة؛ يكفي مسار فرز صغير لطرود كرتونية خفيفة.\n\nهدف التعلم: فهم تصميم أنظمة الأتمتة متعددة الحساسات، التحكم بمحرك DC عالي التيار، دمج أكثر من معيار لاتخاذ القرار، وبناء آلية ميكانيكية قابلة للاختبار والمعايرة.',
    categoryKey: 'electronics-learning',
    difficulty: 'ADVANCED',
    estimatedDurationMinutes: 660,
    coverImageUrl: coverFor('najah-packsort-smart-package-sorter'),
    status: 'PUBLISHED',
    components: [
      {
        name: 'Arduino Mega 2560',
        materialType: 'Arduino Mega 2560',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: false,
        keywords: ['arduino mega', 'mega 2560'],
        notes: 'SOURCE controller. Not mapped to Uno concept (Uno ≠ Mega).',
      },
      {
        name: 'Arduino Uno',
        materialType: 'Arduino Uno',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['arduino uno', 'barcode path'],
        conceptKey: 'component:arduino-board',
        notes: 'SOURCE: Uno for barcode processing path.',
      },
      {
        name: 'BTS7960 Motor Driver',
        materialType: 'BTS7960 Motor Driver',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['bts7960', 'h-bridge', 'motor driver'],
        alternatives: ['H-Bridge Motor Driver'],
      },
      {
        name: 'محرك DC 12V',
        materialType: 'DC Motor',
        categoryKey: 'motors-mechanical',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['dc motor', '12v', 'conveyor'],
        conceptKey: 'component:dc-gear-motors',
      },
      {
        name: 'Servo Motor',
        materialType: 'Servo Motor',
        categoryKey: 'motors-mechanical',
        quantity: 2,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['servo', 'mg996r', 'sg90', 'pusher'],
        conceptKey: 'component:servo-motor',
        notes: 'SOURCE family; qty adapted for two exits (IMPACTLOOP ADAPTATION).',
      },
      {
        name: 'حساس Ultrasonic HC-SR04',
        materialType: 'Ultrasonic Sensor',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: false,
        keywords: ['ultrasonic', 'hc-sr04', 'distance'],
        conceptKey: 'component:ultrasonic-distance-sensor',
      },
      {
        name: 'حساس IR',
        materialType: 'IR Obstacle Sensor',
        categoryKey: 'electronics-components',
        quantity: 2,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['ir', 'infrared', 'obstacle'],
        alternatives: ['IR Sensor'],
        notes: 'SOURCE family; qty adaptation for educational lane.',
      },
      {
        name: 'ESP32',
        materialType: 'ESP32 Development Board',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'OPTIONAL_MATERIAL',
        required: false,
        substitute: true,
        keywords: ['esp32', 'wifi', 'monitoring'],
        alternatives: ['ESP32'],
      },
      {
        name: 'شاشة LCD',
        materialType: '16x2 LCD Display',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['lcd', '16x2', 'display'],
        alternatives: ['LCD Display'],
      },
      {
        name: 'لوحة مفاتيح 4x4',
        materialType: 'Keypad',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['keypad', '4x4'],
      },
      {
        name: 'Barcode Scanner',
        materialType: 'Barcode Scanner',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: false,
        keywords: ['barcode', 'scanner'],
        notes: 'INTENTIONAL GAP — live marketplace has no compatible listing.',
      },
      {
        name: 'TCS3200 Color Sensor',
        materialType: 'TCS3200 Color Sensor',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: false,
        keywords: ['tcs3200', 'color sensor'],
        notes: 'INTENTIONAL GAP — live marketplace has no color-sensor listing.',
      },
      {
        name: 'مواد إطار/حزام ناقل صغير',
        materialType: 'Plywood Sheet',
        categoryKey: 'wood-boards',
        quantity: 1,
        unit: 'panel',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['plywood', 'frame', 'conveyor'],
        alternatives: ['Acrylic Sheet', 'Aluminum Angle'],
        conceptKey: 'component:plywood-panel',
        notes: 'IMPACTLOOP ADAPTATION: plywood/aluminum/acrylic alternatives.',
      },
      {
        name: 'مفتاح طوارئ / Push Switch',
        materialType: 'Push Button Pack',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'pack',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['emergency stop', 'push button', 'switch'],
        alternatives: ['Toggle Switch Pack'],
      },
    ],
    steps: [
      {
        title: 'تحضير قاعدة الحزام',
        description:
          'ابنِ قاعدة صغيرة للحزام الناقل وحدد نقطة دخول الطرد ونقطتي الفرز. استخدم مواد خفيفة مثل الكرتون المقوى أو الخشب الرقائقي.',
      },
      {
        title: 'تشغيل محرك الحزام بأمان',
        description:
          'صِل DC Motor مع BTS7960 واختبر تشغيل الحزام بسرعات آمنة قبل إضافة الحساسات.',
      },
      {
        title: 'تثبيت حساسات الاكتشاف',
        description:
          'ثبّت IR وUltrasonic HC-SR04 وحدد مناطق اكتشاف وجود الطرد وقياس حجمه.',
      },
      {
        title: 'إضافة اللون والـBarcode',
        description:
          'أضف TCS3200 وBarcode Scanner واجمع القراءات بشكل منفصل أولًا قبل دمج القرار.',
      },
      {
        title: 'معايرة Servo pushers',
        description:
          'ثبّت Servo Motors واضبط زواياها بحيث تدفع الطرد بدون تعطيل الحزام.',
      },
      {
        title: 'برمجة قرار الفرز',
        description:
          'برمج Arduino Mega لدمج معايير الفرز، واستخدم Arduino Uno لمسار الـBarcode إذا أردت مطابقة بنية المشروع الأصلي.',
      },
      {
        title: 'واجهة المراقبة',
        description:
          'أضف LCD وKeypad لاختيار وضع الفرز، ثم ESP32 للمراقبة الاختيارية.',
      },
      {
        title: 'اختبار ومعايرة',
        description:
          'اختبر مجموعة طرود صغيرة وسجل أخطاء القياس والفرز ثم عدّل thresholds والتوقيت.',
      },
    ],
    links: [
      {
        linkType: 'ARTICLE',
        url: 'https://repository.najah.edu/items/241261cc-4a4c-4141-bf64-29b500955f08',
        title: 'المشروع الأصلي في مستودع جامعة النجاح',
        sourceName: 'An-Najah Repository',
      },
    ],
    tags: [
      'project-data-03',
      'najah',
      'packsort',
      'automation',
      'arduino',
      'advanced',
    ],
  },
  {
    key: 'najah-automated-liquid-sample-trainer',
    authorEmail: 'majd@learner.com',
    title: 'منصة تدريبية لتحضير عينات سائلة آليًا',
    shortDescription:
      'ابنِ منصة تدريبية تستخدم Arduino Mega وآلية Syringe Dispenser لتحريك وتوزيع كميات محددة من سوائل آمنة مثل الماء الملوّن ضمن تسلسل آلي قابل للبرمجة.',
    description:
      'المشروع الأصلي صُمم لأتمتة تحضير عينات مخبرية باستخدام إبرة متحركة وآلية syringe. نسخة ImpactLoop تعيد صياغة الفكرة كمنصة تعليمية غير طبية: تستخدم ماءً أو سوائل تدريب آمنة لتعلم motion sequencing، توزيع كمية محددة، تنظيف المسار بين الدورات، وتشغيل عدة عمليات بالتتابع.\n\nتنبيه أمان: هذا Learning Project تدريبي فقط. لا يُعرض كجهاز طبي أو تشخيصي ولا يستخدم عينات بشرية أو مواد مخبرية خطرة.\n\nهدف التعلم: التحكم المتسلسل بالحركة، دمج actuator مع liquid dispensing، وبناء state machine بسيطة.',
    categoryKey: 'electronics-learning',
    difficulty: 'INTERMEDIATE',
    estimatedDurationMinutes: 420,
    coverImageUrl: coverFor('najah-automated-liquid-sample-trainer'),
    status: 'PUBLISHED',
    components: [
      {
        name: 'Arduino Mega 2560',
        materialType: 'Arduino Mega 2560',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: false,
        keywords: ['arduino mega', 'mega 2560'],
      },
      {
        name: 'Syringe Dispenser Assembly',
        materialType: 'Syringe Dispenser Assembly',
        categoryKey: 'lab-education',
        quantity: 1,
        unit: 'set',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['syringe', 'dispenser'],
        alternatives: ['Stepper Dispenser Assembly', '3D-Printed Dispenser Assembly'],
        notes: 'IMPACTLOOP adaptation matching source syringe mechanism.',
      },
      {
        name: 'Stepper Motor',
        materialType: 'Stepper Motor',
        categoryKey: 'motors-mechanical',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['stepper', 'nema'],
        conceptKey: 'component:stepper-motor',
      },
      {
        name: 'Stepper Motor Driver',
        materialType: 'A4988 Stepper Motor Driver',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['a4988', 'tb6600', 'stepper driver'],
        alternatives: ['TB6600 Stepper Motor Driver', 'DRV8825 Stepper Motor Driver'],
      },
      {
        name: 'Linear Rail / Slider',
        materialType: 'Linear Rail / Slider',
        categoryKey: 'motors-mechanical',
        quantity: 1,
        unit: 'set',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['linear rail', 'slider'],
        alternatives: ['Linear Actuator'],
      },
      {
        name: 'مزود طاقة',
        materialType: 'Power Supply',
        categoryKey: 'power-batteries',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['power supply', 'psu'],
      },
      {
        name: 'أسلاك توصيل',
        materialType: 'Jumper Wires',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'pack',
        role: 'CONSUMABLE',
        required: true,
        substitute: true,
        keywords: ['jumper', 'dupont'],
        conceptKey: 'component:jumper-wires',
      },
      {
        name: 'أكواب تدريب قابلة لإعادة الاستخدام',
        materialType: 'Plastic Containers',
        categoryKey: 'packaging-containers',
        quantity: 4,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['cups', 'containers', 'training'],
        alternatives: ['Glass Jars'],
        notes: 'IMPACTLOOP ADAPTATION for safe colored-water demos.',
      },
      {
        name: 'دائرة تحسس سعوية (Capacitance)',
        materialType: 'Capacitance Sensing Circuit',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'set',
        role: 'OPTIONAL_MATERIAL',
        required: false,
        substitute: false,
        keywords: ['capacitance', 'liquid sensing'],
        notes: 'INTENTIONAL GAP — SOURCE sensing concept; not in marketplace.',
      },
      {
        name: 'أنابيب / طرف توزيع تدريبي',
        materialType: 'Tubing Set',
        categoryKey: 'lab-education',
        quantity: 1,
        unit: 'set',
        role: 'OPTIONAL_MATERIAL',
        required: false,
        substitute: false,
        keywords: ['tubing', 'needle', 'dispensing'],
        notes: 'USER-PROVIDED / MISSING — safe training tip only; no medical use.',
      },
    ],
    steps: [
      {
        title: 'تثبيت المنصة',
        description:
          'ثبّت Syringe Dispenser على قاعدة مستقرة وحدد مواقع 3–4 أكواب تدريب. استخدم ماءً ملوّنًا فقط.',
      },
      {
        title: 'اختبار الحركة الجافة',
        description:
          'صِل Stepper Motor والـDriver مع Arduino Mega واختبر الحركة بدون سوائل.',
      },
      {
        title: 'معايرة الحجم',
        description:
          'عاير حجم السائل الناتج مقابل عدد خطوات المحرك باستخدام الماء فقط.',
      },
      {
        title: 'إضافة الانتقال بين الأكواب',
        description:
          'أضف حركة انتقال بين الأكواب باستخدام Linear Rail / Slider إن كانت متوفرة.',
      },
      {
        title: 'بناء State Machine',
        description:
          'اكتب state machine لتنفيذ: انتقال → سحب → توزيع → تنظيف → انتقال للعملية التالية.',
      },
      {
        title: 'تحسس اختياري',
        description:
          'أضف sensing اختياريًا لاكتشاف وصول طرف التوزيع أو وجود السائل إن توفرت الدائرة.',
      },
      {
        title: 'تشغيل سلسلة عمليات',
        description:
          'شغّل سلسلة من العمليات على ماء ملوّن وقارن الكميات المطلوبة بالكميات الفعلية.',
      },
    ],
    links: [
      {
        linkType: 'ARTICLE',
        url: 'https://repository.najah.edu/items/8adfce9f-06cd-406a-97f0-e24dcf98bd9c',
        title: 'المشروع الأصلي في مستودع جامعة النجاح',
        sourceName: 'An-Najah Repository',
      },
    ],
    tags: [
      'project-data-03',
      'najah',
      'lab',
      'automation',
      'syringe',
      'intermediate',
    ],
  },
  {
    key: 'najah-wireless-braille-printer',
    authorEmail: 'majd@learner.com',
    title: 'طابعة Braille لاسلكية',
    shortDescription:
      'ابنِ نموذج طابعة Braille يستقبل نصًا لاسلكيًا عبر ESP32، يحوله Arduino Mega إلى نمط Braille، ثم يستخدم Stepper Motors وSolenoid لتحريك الورق وطباعة النقاط البارزة.',
    description:
      'المشروع يجمع البرمجة والاتصالات والـMechatronics في نظام له قيمة تعليمية واجتماعية واضحة (مستند إلى مشروع تخرج في جامعة النجاح). يستقبل ESP32 ملفًا أو نصًا عبر Wi‑Fi، ثم يرسل البيانات إلى Arduino Mega لمعالجة نمط Braille والتحكم بآلية الحركة. يتحرك رأس الطباعة على محور، بينما تتحرك الورقة على المحور الآخر، ويستخدم Solenoid لضغط نقاط Braille على الورق.\n\nهدف التعلم: التحكم الدقيق بمحاور Stepper، التنسيق بين ESP32 وArduino، تحويل البيانات النصية إلى تمثيل ميكانيكي، ومعايرة حركة الطابعة للحصول على pattern منتظم.',
    categoryKey: 'electronics-learning',
    difficulty: 'ADVANCED',
    estimatedDurationMinutes: 780,
    coverImageUrl: coverFor('najah-wireless-braille-printer'),
    status: 'PUBLISHED',
    components: [
      {
        name: 'Arduino Mega 2560',
        materialType: 'Arduino Mega 2560',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: false,
        keywords: ['arduino mega'],
      },
      {
        name: 'ESP32',
        materialType: 'ESP32 Development Board',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['esp32', 'wifi'],
        alternatives: ['ESP32'],
      },
      {
        name: 'حساس Ultrasonic HC-SR04',
        materialType: 'Ultrasonic Sensor',
        categoryKey: 'electronics-components',
        quantity: 2,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: false,
        keywords: ['ultrasonic', 'hc-sr04'],
        conceptKey: 'component:ultrasonic-distance-sensor',
      },
      {
        name: 'NEMA23 Stepper Motor',
        materialType: 'Stepper Motor',
        categoryKey: 'motors-mechanical',
        quantity: 2,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['nema23', 'nema 23', 'stepper'],
        alternatives: ['NEMA 17 Stepper Motor'],
        conceptKey: 'component:stepper-motor',
        notes: 'SOURCE NEMA23; marketplace steppers satisfy via stepper concept.',
      },
      {
        name: 'TB6600 Stepper Driver',
        materialType: 'TB6600 Stepper Motor Driver',
        categoryKey: 'electronics-components',
        quantity: 2,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['tb6600', 'stepper driver'],
        alternatives: ['A4988 Stepper Motor Driver', 'DRV8825 Stepper Motor Driver'],
        notes: 'PARTIAL — live marketplace has limited TB6600 quantity.',
      },
      {
        name: 'Relay Module',
        materialType: 'Relay Module',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['relay', '2-channel'],
      },
      {
        name: 'Solenoid / Electromagnet',
        materialType: 'Solenoid / Electromagnet',
        categoryKey: 'motors-mechanical',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: false,
        keywords: ['solenoid', 'electromagnet', 'embossing'],
      },
      {
        name: 'مفتاح تشغيل/إيقاف',
        materialType: 'Toggle Switch Pack',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'pack',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['switch', 'on off'],
      },
      {
        name: 'مزود طاقة',
        materialType: 'Power Supply',
        categoryKey: 'power-batteries',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['power supply'],
      },
      {
        name: 'شاشة LCD 16x2',
        materialType: '16x2 LCD Display',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['lcd', '16x2'],
        alternatives: ['LCD Display'],
      },
      {
        name: 'لوحة مفاتيح 4x4',
        materialType: 'Keypad',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['keypad', '4x4'],
      },
      {
        name: 'نظام قضبان/سكة خطية',
        materialType: 'Linear Rail / Slider',
        categoryKey: 'motors-mechanical',
        quantity: 1,
        unit: 'set',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['linear rail', 'metal rods'],
        alternatives: ['Metal Rods'],
        notes: 'SOURCE rods; ImpactLoop linear rail can substitute.',
      },
      {
        name: 'GT2 Pulley',
        materialType: 'Pulley',
        categoryKey: 'motors-mechanical',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['gt2', 'pulley'],
        alternatives: ['Pulley Set'],
      },
      {
        name: 'حزام توقيت GT2',
        materialType: 'GT2 Timing Belt',
        categoryKey: 'motors-mechanical',
        quantity: 1,
        unit: 'meter',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: false,
        keywords: ['gt2', 'timing belt'],
        notes: 'INTENTIONAL GAP — no GT2 belt listing in live marketplace.',
      },
      {
        name: 'رأس embossing / Braille pin',
        materialType: 'Braille Embossing Pin',
        categoryKey: 'tools-hardware',
        quantity: 1,
        unit: 'piece',
        role: 'TOOL',
        required: false,
        substitute: false,
        keywords: ['braille', 'embossing', 'pin'],
        notes: 'USER-PROVIDED tool tip for paper testing.',
      },
    ],
    steps: [
      {
        title: 'بناء قاعدة الطابعة',
        description:
          'ابنِ قاعدة الطابعة وثبّت محور حركة رأس الطباعة ومحور تحريك الورق.',
      },
      {
        title: 'اختبار محاور Stepper',
        description:
          'صِل NEMA23 مع TB6600 واختبر كل محور منفصلًا وحدد حدود الحركة.',
      },
      {
        title: 'اختبار Solenoid',
        description:
          'ثبّت Solenoid ورأس embossing واختبر ضغطة واحدة على ورق تجريبي.',
      },
      {
        title: 'برمجة أنماط Braille',
        description:
          'أضف Arduino Mega وبرمج mapping مبسطًا للحروف إلى Braille dot patterns.',
      },
      {
        title: 'ربط ESP32',
        description:
          'أضف ESP32 لإرسال النص إلى Arduino عبر Serial/Wi‑Fi.',
      },
      {
        title: 'واجهة محلية',
        description:
          'صِل LCD وKeypad لعرض الحالة وتنفيذ أوامر محلية.',
      },
      {
        title: 'معايرة المسافات',
        description:
          'عاير المسافات بين النقاط والحروف والصفوف باستخدام نمط اختبار قصير.',
      },
      {
        title: 'اختبار نص قصير',
        description:
          'اختبر نصًا قصيرًا أولًا، ثم أضف word wrapping والملفات الأكبر تدريجيًا.',
      },
    ],
    links: [
      {
        linkType: 'ARTICLE',
        url: 'https://repository.najah.edu/items/495ae9d1-ec43-45aa-86db-deb180748c37',
        title: 'المشروع الأصلي في مستودع جامعة النجاح',
        sourceName: 'An-Najah Repository',
      },
      {
        linkType: 'PDF',
        url: 'https://repository.najah.edu/bitstreams/a1b4ed0c-6909-4b7a-a0ba-b67fadf0e4fc/download',
        title: 'تقرير مشروع التخرج',
        sourceName: 'An-Najah Repository',
      },
    ],
    tags: [
      'project-data-03',
      'najah',
      'braille',
      'accessibility',
      'stepper',
      'advanced',
    ],
  },
  {
    key: 'najah-rootrise-cnc-plant-care',
    authorEmail: 'learner@learner.com',
    title: 'RootRise — نظام CNC للعناية بالنباتات',
    shortDescription:
      'ابنِ نظام CNC يتحرك فوق مجموعة أصص، يقرأ رطوبة التربة ومستوى الماء والإضاءة، ثم ينفذ ريًا موجّهًا لكل نبتة ويعرض القراءات على LCD.',
    description:
      'RootRise في المشروع الأصلي يتحرك على محاور لخدمة عدة أصص مع Soil Moisture وLDR وWater Level Sensors. نسخة ImpactLoop تركز على الجزء التعليمي الأكثر قابلية للبناء: حركة CNC فوق عدة أصص + قياس رطوبة التربة + ري موجّه + مراقبة الضوء والماء.\n\nهدف التعلم: دمج motion control مع sensing واتخاذ القرار، وتصميم نظام يخدم عدة نقاط بدل حساس ثابت.',
    categoryKey: 'robotics',
    difficulty: 'ADVANCED',
    estimatedDurationMinutes: 660,
    coverImageUrl: coverFor('najah-rootrise-cnc-plant-care'),
    status: 'PUBLISHED',
    components: [
      {
        name: 'Stepper Motor',
        materialType: 'Stepper Motor',
        categoryKey: 'motors-mechanical',
        quantity: 2,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['stepper', 'cnc'],
        conceptKey: 'component:stepper-motor',
      },
      {
        name: 'Stepper Motor Driver',
        materialType: 'A4988 Stepper Motor Driver',
        categoryKey: 'electronics-components',
        quantity: 2,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['a4988', 'stepper driver'],
        alternatives: ['TB6600 Stepper Motor Driver'],
      },
      {
        name: 'Linear Rail / Slider',
        materialType: 'Linear Rail / Slider',
        categoryKey: 'motors-mechanical',
        quantity: 2,
        unit: 'set',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['linear rail', 'cnc'],
        notes: 'PARTIAL/ALTERNATIVE vs full XYZ source design.',
      },
      {
        name: 'حساس رطوبة التربة',
        materialType: 'Soil Moisture Sensor',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: false,
        keywords: ['soil moisture'],
      },
      {
        name: 'Servo Motor',
        materialType: 'Servo Motor',
        categoryKey: 'motors-mechanical',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['servo', 'probe arm'],
        conceptKey: 'component:servo-motor',
      },
      {
        name: 'حساس ضوء LDR',
        materialType: 'Light Sensor',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['ldr', 'light sensor'],
        alternatives: ['LDR Light Sensor'],
      },
      {
        name: 'حساس مستوى الماء',
        materialType: 'Water Level Sensor',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: false,
        keywords: ['water level'],
      },
      {
        name: 'مضخة ماء صغيرة',
        materialType: 'Pump',
        categoryKey: 'motors-mechanical',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['water pump', 'pump'],
      },
      {
        name: 'شاشة LCD',
        materialType: 'LCD Display',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['lcd'],
        alternatives: ['16x2 LCD Display'],
      },
      {
        name: 'لوحة مفاتيح 4x4',
        materialType: 'Keypad',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['keypad'],
      },
      {
        name: 'لوحة تحكم Arduino Mega',
        materialType: 'Arduino Mega 2560',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['arduino mega', 'controller'],
        alternatives: ['Arduino Uno'],
        notes: 'IMPACTLOOP ADAPTATION recommended controller.',
      },
      {
        name: 'أنابيب وحاوية ماء',
        materialType: 'Tubing Set',
        categoryKey: 'packaging-containers',
        quantity: 1,
        unit: 'set',
        role: 'OPTIONAL_MATERIAL',
        required: false,
        substitute: false,
        keywords: ['tubing', 'water container'],
        notes: 'USER-PROVIDED / MISSING — IMPACTLOOP ADAPTATION.',
      },
    ],
    steps: [
      {
        title: 'بناء إطار XY',
        description:
          'ابنِ إطار XY صغير يغطي 2–4 أصص بدل النظام الكامل ذي ستة أصص.',
      },
      {
        title: 'تعيين إحداثيات الأصص',
        description:
          'اختبر حركة المحورين وحدد إحداثية كل أصيص.',
      },
      {
        title: 'تثبيت حساس الرطوبة',
        description:
          'ثبّت Soil Moisture Sensor على حامل يتحرك للأسفل باستخدام Servo أو آلية بسيطة.',
      },
      {
        title: 'ضبط المضخة',
        description:
          'صِل Water Pump وحدد مدة تشغيل تعطي كمية ماء مناسبة للاختبار.',
      },
      {
        title: 'إضافة الحساسات والواجهة',
        description:
          'أضف Water Level Sensor وLDR ثم LCD/Keypad لعرض القراءات والتحكم اليدوي.',
      },
      {
        title: 'برمجة دورة الري',
        description:
          'برمج دورة تمر على كل أصيص: انتقال → قياس → قرار ري → تسجيل الحالة.',
      },
      {
        title: 'اختبار السيناريوهات',
        description:
          'اختبر سيناريوهات تربة جافة/رطبة ومستوى ماء منخفض واضبط thresholds.',
      },
    ],
    links: [
      {
        linkType: 'ARTICLE',
        url: 'https://repository.najah.edu/items/6da9a942-6c25-4334-ad76-68ba4254c5b4',
        title: 'المشروع الأصلي في مستودع جامعة النجاح',
        sourceName: 'An-Najah Repository',
      },
    ],
    tags: [
      'project-data-03',
      'najah',
      'rootrise',
      'cnc',
      'plants',
      'advanced',
    ],
  },
  {
    key: 'najah-henna-cnc-pattern-machine',
    authorEmail: 'israa@learner.com',
    title: 'آلة CNC لرسم نقوش الحناء',
    shortDescription:
      'ابنِ منصة CNC صغيرة تحول تصميمًا رقميًا إلى حركة X/Y دقيقة وتستخدم Syringe Pump لرسم نمط باستخدام سائل تدريبي، مع Raspberry Pi Camera لالتقاط مساحة الرسم.',
    description:
      'المشروع الأصلي يجمع Arduino Uno وRaspberry Pi وPi Camera وStepper Motors مع Syringe Pump. في ImpactLoop نحافظ على الفكرة الهندسية والثقافية لكن نجعل مرحلة التعلم والاختبار على ورق أو لوح تدريب أولًا، بحيث يركز المتعلم على G-code، motion calibration، image-to-coordinates والـdispensing بدون الحاجة لاختبار مباشر على الجلد.\n\nهدف التعلم: فهم مبادئ CNC وG-code، التحكم الدقيق بمحاور Stepper، والتنسيق بين Raspberry Pi وArduino.',
    categoryKey: 'robotics',
    difficulty: 'INTERMEDIATE',
    estimatedDurationMinutes: 540,
    coverImageUrl: coverFor('najah-henna-cnc-pattern-machine'),
    status: 'PUBLISHED',
    components: [
      {
        name: 'Arduino Uno',
        materialType: 'Arduino Uno',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: false,
        keywords: ['arduino uno'],
        conceptKey: 'component:arduino-board',
      },
      {
        name: 'Raspberry Pi',
        materialType: 'Raspberry Pi',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['raspberry pi', 'pi 4'],
        alternatives: ['Raspberry Pi 3B', 'Raspberry Pi Kit'],
        conceptKey: 'component:raspberry-pi',
      },
      {
        name: 'Raspberry Pi Camera',
        materialType: 'Camera Module',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['pi camera', 'camera module'],
      },
      {
        name: 'Stepper Motor',
        materialType: 'Stepper Motor',
        categoryKey: 'motors-mechanical',
        quantity: 3,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['stepper', 'x y syringe'],
        conceptKey: 'component:stepper-motor',
        notes: 'SOURCE design: X + Y + syringe mechanism.',
      },
      {
        name: 'A4988 Stepper Driver',
        materialType: 'A4988 Stepper Motor Driver',
        categoryKey: 'electronics-components',
        quantity: 3,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['a4988'],
        alternatives: ['TB6600 Stepper Motor Driver', 'DRV8825 Stepper Motor Driver'],
        notes: 'PARTIAL — limited A4988 listings vs qty 3.',
      },
      {
        name: 'Servo SG90',
        materialType: 'Servo Motor',
        categoryKey: 'motors-mechanical',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['sg90', 'micro servo'],
        conceptKey: 'component:servo-motor',
      },
      {
        name: 'حساس IR',
        materialType: 'IR Obstacle Sensor',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['ir sensor'],
        alternatives: ['IR Sensor'],
      },
      {
        name: 'بطارية / مزود طاقة',
        materialType: 'Power Supply',
        categoryKey: 'power-batteries',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['battery', 'power'],
        alternatives: ['Battery'],
      },
      {
        name: 'نظام قضبان خطية',
        materialType: 'Linear Rail / Slider',
        categoryKey: 'motors-mechanical',
        quantity: 2,
        unit: 'set',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['linear rail', 'rods'],
      },
      {
        name: 'GT2 Pulley',
        materialType: 'Pulley',
        categoryKey: 'motors-mechanical',
        quantity: 2,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['gt2', 'pulley'],
        alternatives: ['Pulley Set'],
      },
      {
        name: 'حزام توقيت GT2',
        materialType: 'GT2 Timing Belt',
        categoryKey: 'motors-mechanical',
        quantity: 2,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: false,
        keywords: ['gt2 belt'],
        notes: 'INTENTIONAL GAP — no GT2 belt listing.',
      },
      {
        name: 'Syringe Dispenser Assembly',
        materialType: 'Syringe Dispenser Assembly',
        categoryKey: 'lab-education',
        quantity: 1,
        unit: 'set',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['syringe pump', 'dispenser'],
        alternatives: ['Stepper Dispenser Assembly'],
      },
      {
        name: 'أسلاك توصيل',
        materialType: 'Jumper Wires',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'pack',
        role: 'CONSUMABLE',
        required: true,
        substitute: true,
        keywords: ['jumper'],
        conceptKey: 'component:jumper-wires',
      },
    ],
    steps: [
      {
        title: 'بناء إطار CNC',
        description:
          'ابنِ إطار CNC صغير لمحوري X وY وثبّت Stepper Motors والـrails.',
      },
      {
        title: 'ضبط سواقات المحركات',
        description:
          'صِل A4988 واضبط current limits ثم اختبر الحركة بمسافات قصيرة.',
      },
      {
        title: 'تثبيت أداة الرسم',
        description:
          'ثبّت Syringe Dispenser كأداة الرسم واختبر توزيع الماء الملوّن على ورق تدريب (ليس على الجلد).',
      },
      {
        title: 'تشغيل حركة Arduino',
        description:
          'صِل Arduino Uno وشغّل GRBL أو منطق حركة مناسب لإحداثيات X/Y.',
      },
      {
        title: 'كاميرا مساحة الرسم',
        description:
          'استخدم Raspberry Pi Camera لتحديد مساحة الرسم أو إدخال تصميم محدد مسبقًا.',
      },
      {
        title: 'تحويل النمط إلى مسار',
        description:
          'حوّل النمط إلى نقاط/مسار ثم إلى G-code أو أوامر حركة.',
      },
      {
        title: 'Dry-run ثم سائل تدريبي',
        description:
          'نفذ dry-run بدون سائل، ثم اختبارًا بسائل تدريبي واضبط السرعة والتدفق.',
      },
      {
        title: 'تحسين اختياري',
        description:
          'أضف app/control layer كتحسين اختياري بعد استقرار الحركة الأساسية.',
      },
    ],
    links: [
      {
        linkType: 'ARTICLE',
        url: 'https://repository.najah.edu/items/0db2bf18-9853-47f1-b698-a0ea01b20821',
        title: 'المشروع الأصلي في مستودع جامعة النجاح',
        sourceName: 'An-Najah Repository',
      },
      {
        linkType: 'PDF',
        url: 'https://repository.najah.edu/bitstreams/66f6951f-3f04-4365-970d-4b8a59e85fce/download',
        title: 'تقرير مشروع التخرج',
        sourceName: 'An-Najah Repository',
      },
      {
        linkType: 'OTHER',
        url: 'https://repository.najah.edu/bitstreams/d828f8df-1b3b-47b1-bb4a-2aa1c3b4a6db/download',
        title: 'عرض المشروع',
        sourceName: 'An-Najah Repository',
      },
      {
        linkType: 'OTHER',
        url: 'https://repository.najah.edu/bitstreams/f252a943-8190-4c58-ac3d-7f2ff874d026/download',
        title: 'فيديو تجريبي',
        sourceName: 'An-Najah Repository',
      },
    ],
    tags: [
      'project-data-03',
      'najah',
      'henna',
      'cnc',
      'raspberry-pi',
      'intermediate',
    ],
  },
  {
    key: 'najah-map-go-ros-lidar-robot',
    authorEmail: 'majd@learner.com',
    title: 'MAP&GO — روبوت ملاحة باستخدام ROS وLiDAR',
    shortDescription:
      'ابنِ روبوتًا تعليميًا يعتمد على Raspberry Pi وLiDAR لتجربة ROS، مشاهدة بيانات الحساسات في RViz، إنشاء خريطة باستخدام SLAM، ثم اختبار الملاحة داخل مساحة صغيرة.',
    description:
      'MAP&GO مستوحى من مختبر روبوتات يعتمد على Raspberry Pi وMotor Driver وLiDAR ودعم Camera. نسخة ImpactLoop تركز على بناء الروبوت محليًا وتشغيل ROS/SLAM عليه؛ الوصول عن بعد يكون extension اختياري بعد نجاح الحركة والـmapping.\n\nهدف التعلم: بنية mobile robot، قراءة LiDAR، أساسيات ROS، وبناء خريطة 2D باستخدام SLAM.',
    categoryKey: 'robotics',
    difficulty: 'ADVANCED',
    estimatedDurationMinutes: 660,
    coverImageUrl: coverFor('najah-map-go-ros-lidar-robot'),
    status: 'PUBLISHED',
    components: [
      {
        name: 'Raspberry Pi',
        materialType: 'Raspberry Pi',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['raspberry pi'],
        alternatives: ['Raspberry Pi 3B', 'Raspberry Pi Kit'],
        conceptKey: 'component:raspberry-pi',
      },
      {
        name: 'حساس LiDAR ثنائي الأبعاد',
        materialType: 'LiDAR Sensor',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: false,
        keywords: ['lidar', 'rplidar', 'slam'],
      },
      {
        name: 'Motor Driver',
        materialType: 'L298N Motor Driver',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['motor driver', 'l298n'],
        alternatives: ['H-Bridge Motor Driver', 'Motor Driver'],
        conceptKey: 'component:motor-driver',
      },
      {
        name: 'محركات DC مع Encoder',
        materialType: 'DC Motor',
        categoryKey: 'motors-mechanical',
        quantity: 2,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['dc motor', 'encoder', 'gear motor'],
        conceptKey: 'component:dc-gear-motors',
        notes: 'IMPACTLOOP ADAPTATION for mobile base.',
      },
      {
        name: 'عجلات',
        materialType: 'Rubber Wheels',
        categoryKey: 'motors-mechanical',
        quantity: 2,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['wheels'],
        alternatives: ['Wheel / Caster'],
        conceptKey: 'component:rubber-wheels',
      },
      {
        name: 'عجلة كاستر',
        materialType: 'Caster Wheels',
        categoryKey: 'motors-mechanical',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['caster'],
        alternatives: ['Wheel / Caster'],
      },
      {
        name: 'وحدة كاميرا',
        materialType: 'Camera Module',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'OPTIONAL_MATERIAL',
        required: false,
        substitute: true,
        keywords: ['camera'],
      },
      {
        name: 'هيكل روبوت / قاعدة',
        materialType: 'Acrylic Sheet',
        categoryKey: 'plastics-acrylic',
        quantity: 1,
        unit: 'sheet',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['chassis', 'frame'],
        alternatives: ['Plywood Sheet', 'MDF Offcuts'],
        conceptKey: 'component:acrylic-sheets',
        notes: 'ALTERNATIVE for SOURCE 3D-printed chassis.',
      },
      {
        name: 'نظام طاقة / بطارية',
        materialType: 'Battery',
        categoryKey: 'power-batteries',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['battery', 'power'],
        alternatives: ['Power Supply', 'Battery Holder'],
      },
    ],
    steps: [
      {
        title: 'بناء قاعدة الحركة',
        description:
          'ابنِ قاعدة روبوت بعجلتين وثبّت motors والـencoder والـmotor driver.',
      },
      {
        title: 'تثبيت Raspberry Pi وLiDAR',
        description:
          'ثبت Raspberry Pi وLiDAR في نقطة مستقرة ومركزية على الهيكل.',
      },
      {
        title: 'اختبار Teleoperation',
        description:
          'اختبر teleoperation والحركة الأمامية والدوران قبل تشغيل SLAM.',
      },
      {
        title: 'تشغيل ROS وRViz',
        description:
          'شغّل ROS وتأكد من ظهور بيانات LiDAR وodometry في RViz.',
      },
      {
        title: 'بناء خريطة SLAM',
        description:
          'نفذ جولة بطيئة في مساحة صغيرة لبناء خريطة 2D باستخدام SLAM.',
      },
      {
        title: 'اختبار الملاحة',
        description:
          'احفظ الخريطة وحدد نقطة هدف واختبر navigation تدريجيًا.',
      },
      {
        title: 'إضافة اختيارية',
        description:
          'أضف camera/remote access كمرحلة اختيارية بعد نجاح الملاحة الأساسية.',
      },
    ],
    links: [
      {
        linkType: 'ARTICLE',
        url: 'https://repository.najah.edu/items/3d3a921d-0552-4e68-8bee-ccaca4ef0542',
        title: 'المشروع الأصلي في مستودع جامعة النجاح',
        sourceName: 'An-Najah Repository',
      },
    ],
    tags: [
      'project-data-03',
      'najah',
      'map-go',
      'ros',
      'lidar',
      'advanced',
    ],
  },
  {
    key: 'najah-bottle-separator-robot',
    authorEmail: 'majd@learner.com',
    title: 'روبوت فرز الزجاجات المعدنية والبلاستيكية',
    shortDescription:
      'ابنِ روبوتًا يكتشف الزجاجات بالكاميرا، يقترب منها، يلتقطها بذراع بسيطة، ثم يستخدم Metal Sensor لتمييز المعدن عن البلاستيك ووضع كل قطعة في الحاوية المناسبة.',
    description:
      'يجمع المشروع بين Computer Vision والروبوتات وإعادة التدوير. يستخدم Raspberry Pi لمعالجة صورة الكاميرا وإرسال أوامر إلى Arduino الذي يتحكم بالحركة والذراع. في المشروع الأصلي تُستخدم OAK-D لاكتشاف الأجسام، بينما يحدد Metal Sensor فعليًا ما إذا كانت الزجاجة معدنية أم بلاستيكية قبل عملية الفرز — ولا يُنسب قرار المادة للـAI وحده.\n\nهدف التعلم: فصل perception عن actuation، الاتصال بين Raspberry Pi وArduino، والتحكم بذراع روبوتية.',
    categoryKey: 'recycling-crafts',
    difficulty: 'ADVANCED',
    estimatedDurationMinutes: 780,
    coverImageUrl: coverFor('najah-bottle-separator-robot'),
    status: 'PUBLISHED',
    components: [
      {
        name: 'Raspberry Pi',
        materialType: 'Raspberry Pi 3B',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['raspberry pi 3'],
        alternatives: ['Raspberry Pi', 'Raspberry Pi Kit'],
        conceptKey: 'component:raspberry-pi',
      },
      {
        name: 'Arduino',
        materialType: 'Arduino Uno',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['arduino'],
        alternatives: ['Arduino Mega 2560'],
        conceptKey: 'component:arduino-board',
      },
      {
        name: 'كاميرا OAK-D',
        materialType: 'OAK-D Camera',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: false,
        keywords: ['oak-d', 'depthai', 'camera'],
        notes: 'INTENTIONAL GAP — SOURCE camera; not in marketplace.',
      },
      {
        name: 'Stepper Motor',
        materialType: 'Stepper Motor',
        categoryKey: 'motors-mechanical',
        quantity: 5,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['stepper'],
        conceptKey: 'component:stepper-motor',
        notes: 'SOURCE functional count; may be PARTIAL across marketplace qty.',
      },
      {
        name: 'Stepper Motor Driver',
        materialType: 'A4988 Stepper Motor Driver',
        categoryKey: 'electronics-components',
        quantity: 5,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['a4988', 'tb6600'],
        alternatives: ['TB6600 Stepper Motor Driver', 'DRV8825 Stepper Motor Driver'],
        notes: 'PARTIAL — IMPACTLOOP ADAPTATION drivers; limited supply.',
      },
      {
        name: 'Servo Motor',
        materialType: 'Servo Motor',
        categoryKey: 'motors-mechanical',
        quantity: 2,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['servo', 'gripper'],
        conceptKey: 'component:servo-motor',
      },
      {
        name: 'حساس Ultrasonic HC-SR04',
        materialType: 'Ultrasonic Sensor',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: false,
        keywords: ['ultrasonic', 'hc-sr04'],
        conceptKey: 'component:ultrasonic-distance-sensor',
      },
      {
        name: 'Metal Sensor',
        materialType: 'Metal Sensor',
        categoryKey: 'electronics-components',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: false,
        keywords: ['metal sensor', 'inductive', 'metal detector'],
        notes: 'INTENTIONAL GAP — SOURCE sorting logic; no true metal sensor listing.',
      },
      {
        name: 'هيكل ذراع / Gripper',
        materialType: 'Acrylic Sheet',
        categoryKey: 'plastics-acrylic',
        quantity: 1,
        unit: 'sheet',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['gripper', 'arm', 'acrylic'],
        alternatives: ['Plywood Sheet'],
        conceptKey: 'component:acrylic-sheets',
      },
      {
        name: 'قاعدة وعجلات',
        materialType: 'Rubber Wheels',
        categoryKey: 'motors-mechanical',
        quantity: 1,
        unit: 'set',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['wheels', 'base'],
        alternatives: ['Caster Wheels', 'Wheel / Caster'],
        conceptKey: 'component:rubber-wheels',
      },
      {
        name: 'نظام طاقة',
        materialType: 'Battery',
        categoryKey: 'power-batteries',
        quantity: 1,
        unit: 'piece',
        role: 'REQUIRED_MATERIAL',
        required: true,
        substitute: true,
        keywords: ['battery', 'power'],
        alternatives: ['Power Supply'],
      },
    ],
    steps: [
      {
        title: 'بناء قاعدة الحركة',
        description:
          'ابنِ قاعدة الحركة واختبر motors بدون الذراع أو الكاميرا.',
      },
      {
        title: 'إيقاف آمن بالموجات فوق الصوتية',
        description:
          'ثبّت Ultrasonic HC-SR04 وأوقف الحركة تلقائيًا عند الاقتراب من جسم ضمن مسافة محددة.',
      },
      {
        title: 'بناء ذراع مبسطة',
        description:
          'ابنِ ذراعًا مبسطة بمحورين مع gripper واختبر التقاط زجاجة فارغة.',
      },
      {
        title: 'مسار الرؤية',
        description:
          'شغّل camera pipeline للكشف عن وجود Bottle مقابل Other؛ لا تربط بعد بين الرؤية ونوع المادة.',
      },
      {
        title: 'تسلسل الالتقاط',
        description:
          'بعد اكتشاف الزجاجة، نفذ sequence: اقتراب → توقف → التقاط.',
      },
      {
        title: 'فرز بالمستشعر المعدني',
        description:
          'مرر القطعة أمام Metal Sensor وحدد Metal/Plastic بناءً على الحساس (وليس AI وحده).',
      },
      {
        title: 'وضع القطعة في الحاوية',
        description:
          'حرّك الذراع/السلة إلى حاوية الفرز المناسبة.',
      },
      {
        title: 'اختبار وتسجيل الأخطاء',
        description:
          'اختبر تحت إضاءات ومسافات مختلفة وسجل false detections وأخطاء الالتقاط.',
      },
    ],
    links: [
      {
        linkType: 'ARTICLE',
        url: 'https://repository.najah.edu/items/57414b44-80bd-4d60-b2d0-f25b98fa88f9',
        title: 'المشروع الأصلي في مستودع جامعة النجاح',
        sourceName: 'An-Najah Repository',
      },
      {
        linkType: 'PDF',
        url: 'https://repository.najah.edu/bitstreams/8718da8a-9bfb-4e66-8845-f09a4271196d/download',
        title: 'تقرير مشروع التخرج',
        sourceName: 'An-Najah Repository',
      },
    ],
    tags: [
      'project-data-03',
      'najah',
      'recycling',
      'vision',
      'robotics',
      'advanced',
    ],
  },
];
