-- Dev-only helper: remove duplicate driver delivery notifications for one user.
-- Review results before running DELETE in local/dev databases.
--
-- Example: replace :driver_user_id with your driver users.id.
--
-- Preview duplicates:
-- SELECT user_id, notification_type, related_entity_type, related_entity_id, COUNT(*) AS count
-- FROM notifications
-- WHERE user_id = :driver_user_id
--   AND notification_type LIKE 'DRIVER_%'
-- GROUP BY 1,2,3,4
-- HAVING COUNT(*) > 1;
--
-- Keep the oldest row per duplicate group:
-- DELETE FROM notifications n
-- USING (
--   SELECT id,
--          ROW_NUMBER() OVER (
--            PARTITION BY user_id, notification_type, related_entity_type, related_entity_id
--            ORDER BY created_at ASC, id ASC
--          ) AS row_num
--   FROM notifications
--   WHERE user_id = :driver_user_id
--     AND notification_type LIKE 'DRIVER_%'
-- ) d
-- WHERE n.id = d.id
--   AND d.row_num > 1;
