import type {
  MaterialCondition,
  MaterialStatus,
} from '../../src/generated/prisma/client.js';

export const MY_MATERIALS_SEED_PREFIX = '[my-materials-seed]';

export const myMaterialsSeedMarker = (key: string): string =>
  `${MY_MATERIALS_SEED_PREFIX} key:${key}`;

export type SupplierMyMaterialSeedSpec = {
  key: string;
  title: string;
  summary: string;
  categoryNameEn: string;
  location: { country: string; city: string; area: string };
  status: MaterialStatus;
  condition: MaterialCondition;
  isFree: boolean;
  price: number | null;
  quantity: number;
  unit: string;
  materialType: string;
  pickupAllowed: boolean;
  deliveryAllowed: boolean;
  viewsCount: number;
  imageUrls: string[];
  tags?: string[];
};

/** Stable Unsplash direct URLs used elsewhere in project seeds. */
const IMG = {
  arduino:
    'https://images.unsplash.com/photo-1553406830-ef2513450d76?auto=format&fit=crop&w=1200&q=80',
  circuit:
    'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
  workshop:
    'https://images.unsplash.com/photo-1581092921461-eab62e97a780?auto=format&fit=crop&w=1200&q=80',
  components:
    'https://images.unsplash.com/photo-1581092335397-9583eb92d232?auto=format&fit=crop&w=1200&q=80',
  breadboard:
    'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1200&q=80',
  motors:
    'https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?auto=format&fit=crop&w=1200&q=80',
  soldering:
    'https://images.unsplash.com/photo-1621761195602-9883b0a0955d?auto=format&fit=crop&w=1200&q=80',
  pcb:
    'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
  display:
    'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=1200&q=80',
  cables:
    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=80',
} as const;

const LOC = {
  nablusIndustrial: {
    country: 'Palestine',
    city: 'Nablus',
    area: 'Industrial Area',
  },
  rafidia: { country: 'Palestine', city: 'Nablus', area: 'Rafidia' },
  najah: {
    country: 'Palestine',
    city: 'Nablus',
    area: 'An-Najah University',
  },
  alEinCamp: { country: 'Palestine', city: 'Nablus', area: 'Al Ein Camp' },
} as const;

const ELECTRONICS = 'Electronics';

/** Electronics-focused workshop inventory for seed-supplier@impactloop.test */
export const SUPPLIER_MY_MATERIALS_SEED: SupplierMyMaterialSeedSpec[] = [
  {
    key: 'elec-01-arduino-uno',
    title: 'Arduino Uno Boards',
    summary:
      'Tested Arduino Uno boards from a classroom surplus cabinet, ready for student prototypes.',
    categoryNameEn: ELECTRONICS,
    location: LOC.nablusIndustrial,
    status: 'AVAILABLE',
    condition: 'LIKE_NEW',
    isFree: false,
    price: 45,
    quantity: 8,
    unit: 'pieces',
    materialType: 'Microcontroller boards',
    pickupAllowed: true,
    deliveryAllowed: true,
    viewsCount: 41,
    imageUrls: [IMG.arduino, IMG.circuit],
    tags: ['arduino', 'microcontroller'],
  },
  {
    key: 'elec-02-arduino-nano',
    title: 'Arduino Nano Boards',
    summary: 'Compact Nano boards with USB interface for breadboard projects.',
    categoryNameEn: ELECTRONICS,
    location: LOC.rafidia,
    status: 'AVAILABLE',
    condition: 'GOOD',
    isFree: false,
    price: 38,
    quantity: 12,
    unit: 'pieces',
    materialType: 'Microcontroller boards',
    pickupAllowed: true,
    deliveryAllowed: true,
    viewsCount: 33,
    imageUrls: [IMG.arduino, IMG.breadboard],
    tags: ['arduino', 'nano'],
  },
  {
    key: 'elec-03-esp32',
    title: 'ESP32 Development Boards',
    summary: 'Wi-Fi enabled ESP32 boards with USB programming headers.',
    categoryNameEn: ELECTRONICS,
    location: LOC.najah,
    status: 'AVAILABLE',
    condition: 'NEW',
    isFree: false,
    price: 55,
    quantity: 6,
    unit: 'pieces',
    materialType: 'Microcontroller boards',
    pickupAllowed: true,
    deliveryAllowed: true,
    viewsCount: 36,
    imageUrls: [IMG.circuit],
    tags: ['esp32', 'wifi'],
  },
  {
    key: 'elec-04-raspberry-pi-accessories',
    title: 'Raspberry Pi Accessories',
    summary:
      'GPIO breakout boards, heatsinks, and microSD adapters from retired kits.',
    categoryNameEn: ELECTRONICS,
    location: LOC.alEinCamp,
    status: 'PENDING_RESERVATION',
    condition: 'LIKE_NEW',
    isFree: false,
    price: 65,
    quantity: 4,
    unit: 'sets',
    materialType: 'Single-board computer accessories',
    pickupAllowed: true,
    deliveryAllowed: false,
    viewsCount: 29,
    imageUrls: [IMG.components, IMG.circuit],
    tags: ['raspberry pi', 'accessories'],
  },
  {
    key: 'elec-05-breadboards',
    title: 'Half-size Breadboards',
    summary: 'Clean breadboards for lab benches and student kits.',
    categoryNameEn: ELECTRONICS,
    location: LOC.nablusIndustrial,
    status: 'AVAILABLE',
    condition: 'GOOD',
    isFree: true,
    price: null,
    quantity: 15,
    unit: 'pieces',
    materialType: 'Prototyping boards',
    pickupAllowed: true,
    deliveryAllowed: false,
    viewsCount: 19,
    imageUrls: [IMG.breadboard, IMG.components],
    tags: ['breadboard', 'prototyping'],
  },
  {
    key: 'elec-06-jumper-wires',
    title: 'Jumper Wires Pack',
    summary: 'Assorted male-to-male and male-to-female jumper wire packs.',
    categoryNameEn: ELECTRONICS,
    location: LOC.rafidia,
    status: 'AVAILABLE',
    condition: 'LIKE_NEW',
    isFree: false,
    price: 12,
    quantity: 20,
    unit: 'packs',
    materialType: 'Electronic wiring',
    pickupAllowed: true,
    deliveryAllowed: true,
    viewsCount: 22,
    imageUrls: [IMG.circuit, IMG.cables],
    tags: ['jumper wires', 'breadboard'],
  },
  {
    key: 'elec-07-ultrasonic',
    title: 'Ultrasonic Sensors HC-SR04',
    summary: 'Distance sensors sorted and labeled for robotics projects.',
    categoryNameEn: ELECTRONICS,
    location: LOC.najah,
    status: 'AVAILABLE',
    condition: 'GOOD',
    isFree: false,
    price: 18,
    quantity: 10,
    unit: 'pieces',
    materialType: 'Sensors',
    pickupAllowed: true,
    deliveryAllowed: false,
    viewsCount: 28,
    imageUrls: [IMG.workshop],
    tags: ['sensor', 'ultrasonic'],
  },
  {
    key: 'elec-08-ir-sensors',
    title: 'IR Sensor Modules',
    summary: 'Infrared obstacle detection modules for line-following robots.',
    categoryNameEn: ELECTRONICS,
    location: LOC.alEinCamp,
    status: 'RESERVED',
    condition: 'GOOD',
    isFree: false,
    price: 14,
    quantity: 8,
    unit: 'pieces',
    materialType: 'Sensors',
    pickupAllowed: true,
    deliveryAllowed: false,
    viewsCount: 17,
    imageUrls: [IMG.components],
    tags: ['ir', 'sensor'],
  },
  {
    key: 'elec-09-servo-motors',
    title: 'Servo Motors',
    summary: 'Micro servos removed from retired robotics kits, tested working.',
    categoryNameEn: ELECTRONICS,
    location: LOC.nablusIndustrial,
    status: 'AVAILABLE',
    condition: 'GOOD',
    isFree: false,
    price: 22,
    quantity: 14,
    unit: 'pieces',
    materialType: 'Actuators',
    pickupAllowed: true,
    deliveryAllowed: true,
    viewsCount: 33,
    imageUrls: [IMG.motors, IMG.components],
    tags: ['servo', 'robotics'],
  },
  {
    key: 'elec-10-dc-motors',
    title: 'DC Motors',
    summary: 'Small DC gear motors suitable for car and fan prototypes.',
    categoryNameEn: ELECTRONICS,
    location: LOC.rafidia,
    status: 'PENDING_RESERVATION',
    condition: 'USED',
    isFree: true,
    price: null,
    quantity: 6,
    unit: 'pieces',
    materialType: 'Actuators',
    pickupAllowed: true,
    deliveryAllowed: false,
    viewsCount: 21,
    imageUrls: [IMG.motors],
    tags: ['dc motor', 'robotics'],
  },
  {
    key: 'elec-11-stepper-modules',
    title: 'Stepper Motor Modules',
    summary: 'NEMA17 stepper motors with driver breakout boards.',
    categoryNameEn: ELECTRONICS,
    location: LOC.najah,
    status: 'AVAILABLE',
    condition: 'LIKE_NEW',
    isFree: false,
    price: 85,
    quantity: 3,
    unit: 'sets',
    materialType: 'Actuators',
    pickupAllowed: true,
    deliveryAllowed: true,
    viewsCount: 15,
    imageUrls: [IMG.motors, IMG.circuit],
    tags: ['stepper', 'motor'],
  },
  {
    key: 'elec-12-l298n-drivers',
    title: 'L298N Motor Drivers',
    summary: 'Dual H-bridge motor driver modules for Arduino projects.',
    categoryNameEn: ELECTRONICS,
    location: LOC.alEinCamp,
    status: 'AVAILABLE',
    condition: 'GOOD',
    isFree: false,
    price: 28,
    quantity: 7,
    unit: 'pieces',
    materialType: 'Motor drivers',
    pickupAllowed: true,
    deliveryAllowed: false,
    viewsCount: 24,
    imageUrls: [IMG.circuit],
    tags: ['l298n', 'driver'],
  },
  {
    key: 'elec-13-relay-modules',
    title: 'Relay Modules',
    summary: '5V relay modules for switching lights and small appliances.',
    categoryNameEn: ELECTRONICS,
    location: LOC.nablusIndustrial,
    status: 'RESERVED',
    condition: 'NEW',
    isFree: false,
    price: 16,
    quantity: 9,
    unit: 'pieces',
    materialType: 'Switching modules',
    pickupAllowed: true,
    deliveryAllowed: false,
    viewsCount: 18,
    imageUrls: [IMG.components],
    tags: ['relay', 'switching'],
  },
  {
    key: 'elec-14-led-pack',
    title: 'LED Pack',
    summary: 'Assorted 3mm and 5mm LEDs in red, green, blue, and yellow.',
    categoryNameEn: ELECTRONICS,
    location: LOC.rafidia,
    status: 'AVAILABLE',
    condition: 'NEW',
    isFree: false,
    price: 10,
    quantity: 5,
    unit: 'packs',
    materialType: 'Light emitting diodes',
    pickupAllowed: true,
    deliveryAllowed: true,
    viewsCount: 26,
    imageUrls: [IMG.components, IMG.circuit],
    tags: ['led', 'components'],
  },
  {
    key: 'elec-15-resistor-kit',
    title: 'Resistor Kit',
    summary: 'Labeled resistor assortment from 10Ω to 1MΩ.',
    categoryNameEn: ELECTRONICS,
    location: LOC.najah,
    status: 'AVAILABLE',
    condition: 'LIKE_NEW',
    isFree: false,
    price: 20,
    quantity: 4,
    unit: 'kits',
    materialType: 'Passive components',
    pickupAllowed: true,
    deliveryAllowed: true,
    viewsCount: 31,
    imageUrls: [IMG.components],
    tags: ['resistor', 'kit'],
  },
  {
    key: 'elec-16-capacitor-kit',
    title: 'Capacitor Kit',
    summary: 'Electrolytic and ceramic capacitors in a sorted storage box.',
    categoryNameEn: ELECTRONICS,
    location: LOC.alEinCamp,
    status: 'REUSED',
    condition: 'USED',
    isFree: true,
    price: null,
    quantity: 2,
    unit: 'kits',
    materialType: 'Passive components',
    pickupAllowed: true,
    deliveryAllowed: false,
    viewsCount: 12,
    imageUrls: [IMG.components],
    tags: ['capacitor', 'kit'],
  },
  {
    key: 'elec-17-potentiometers',
    title: 'Potentiometers Pack',
    summary: '10kΩ linear potentiometers for analog input experiments.',
    categoryNameEn: ELECTRONICS,
    location: LOC.nablusIndustrial,
    status: 'AVAILABLE',
    condition: 'GOOD',
    isFree: false,
    price: 15,
    quantity: 10,
    unit: 'packs',
    materialType: 'Passive components',
    pickupAllowed: true,
    deliveryAllowed: false,
    viewsCount: 14,
    imageUrls: [IMG.components],
    tags: ['potentiometer', 'analog'],
  },
  {
    key: 'elec-18-lcd-display',
    title: 'LCD 16x2 Display Modules',
    summary: 'Character LCD modules with I2C backpacks pre-soldered.',
    categoryNameEn: ELECTRONICS,
    location: LOC.rafidia,
    status: 'AVAILABLE',
    condition: 'LIKE_NEW',
    isFree: false,
    price: 32,
    quantity: 5,
    unit: 'pieces',
    materialType: 'Displays',
    pickupAllowed: true,
    deliveryAllowed: true,
    viewsCount: 27,
    imageUrls: [IMG.display, IMG.circuit],
    tags: ['lcd', 'display'],
  },
  {
    key: 'elec-19-oled-display',
    title: 'OLED Display Modules',
    summary: '0.96 inch I2C OLED screens for compact project dashboards.',
    categoryNameEn: ELECTRONICS,
    location: LOC.najah,
    status: 'PENDING_RESERVATION',
    condition: 'NEW',
    isFree: false,
    price: 35,
    quantity: 6,
    unit: 'pieces',
    materialType: 'Displays',
    pickupAllowed: true,
    deliveryAllowed: false,
    viewsCount: 23,
    imageUrls: [IMG.display],
    tags: ['oled', 'display'],
  },
  {
    key: 'elec-20-battery-holders',
    title: 'Battery Holders',
    summary: 'AA and 9V battery holders with leads for portable circuits.',
    categoryNameEn: ELECTRONICS,
    location: LOC.alEinCamp,
    status: 'AVAILABLE',
    condition: 'GOOD',
    isFree: false,
    price: 8,
    quantity: 18,
    unit: 'pieces',
    materialType: 'Power accessories',
    pickupAllowed: true,
    deliveryAllowed: true,
    viewsCount: 11,
    imageUrls: [IMG.components],
    tags: ['battery', 'power'],
  },
  {
    key: 'elec-21-usb-cables',
    title: 'USB Cables',
    summary: 'Micro-USB and USB-C data cables from retired dev kits.',
    categoryNameEn: ELECTRONICS,
    location: LOC.nablusIndustrial,
    status: 'REUSED',
    condition: 'USED',
    isFree: true,
    price: null,
    quantity: 15,
    unit: 'pieces',
    materialType: 'Cables',
    pickupAllowed: true,
    deliveryAllowed: false,
    viewsCount: 16,
    imageUrls: [IMG.cables],
    tags: ['usb', 'cables'],
  },
  {
    key: 'elec-22-pcb-scraps',
    title: 'PCB Scraps',
    summary: 'Copper-clad and etched PCB offcuts for soldering practice.',
    categoryNameEn: ELECTRONICS,
    location: LOC.rafidia,
    status: 'UNAVAILABLE',
    condition: 'NEEDS_REPAIR',
    isFree: false,
    price: 5,
    quantity: 20,
    unit: 'pieces',
    materialType: 'Printed circuit boards',
    pickupAllowed: false,
    deliveryAllowed: false,
    viewsCount: 8,
    imageUrls: [IMG.pcb],
    tags: ['pcb', 'scraps'],
  },
  {
    key: 'elec-23-soldering-boards',
    title: 'Soldering Practice Boards',
    summary: 'Perforated boards and practice pads for soldering workshops.',
    categoryNameEn: ELECTRONICS,
    location: LOC.najah,
    status: 'AVAILABLE',
    condition: 'GOOD',
    isFree: false,
    price: 18,
    quantity: 10,
    unit: 'pieces',
    materialType: 'Prototyping boards',
    pickupAllowed: true,
    deliveryAllowed: false,
    viewsCount: 19,
    imageUrls: [IMG.soldering, IMG.breadboard],
    tags: ['soldering', 'practice'],
  },
  {
    key: 'elec-24-sensor-bundle',
    title: 'Sensor Bundle',
    summary:
      'Mixed temperature, humidity, and light sensor modules in one bundle.',
    categoryNameEn: ELECTRONICS,
    location: LOC.alEinCamp,
    status: 'RESERVED',
    condition: 'LIKE_NEW',
    isFree: false,
    price: 42,
    quantity: 2,
    unit: 'bundles',
    materialType: 'Sensor kits',
    pickupAllowed: true,
    deliveryAllowed: true,
    viewsCount: 34,
    imageUrls: [IMG.workshop, IMG.components],
    tags: ['sensor', 'bundle'],
  },
  {
    key: 'elec-25-esp8266',
    title: 'ESP8266 Wi-Fi Modules',
    summary: 'NodeMCU-style ESP8266 boards for IoT starter projects.',
    categoryNameEn: ELECTRONICS,
    location: LOC.nablusIndustrial,
    status: 'UNAVAILABLE',
    condition: 'NEEDS_REPAIR',
    isFree: false,
    price: 25,
    quantity: 3,
    unit: 'pieces',
    materialType: 'Microcontroller boards',
    pickupAllowed: false,
    deliveryAllowed: false,
    viewsCount: 7,
    imageUrls: [IMG.circuit],
    tags: ['esp8266', 'wifi'],
  },
  {
    key: 'elec-26-multimeter-practice',
    title: 'Multimeter Practice Components',
    summary:
      'Labeled resistors, LEDs, and switches for multimeter training kits.',
    categoryNameEn: ELECTRONICS,
    location: LOC.rafidia,
    status: 'REUSED',
    condition: 'USED',
    isFree: true,
    price: null,
    quantity: 1,
    unit: 'kit',
    materialType: 'Training kits',
    pickupAllowed: true,
    deliveryAllowed: false,
    viewsCount: 9,
    imageUrls: [IMG.workshop],
    tags: ['multimeter', 'training'],
  },
];
