ALTER TYPE "LearningProjectStatus" ADD VALUE IF NOT EXISTS 'CHANGES_REQUESTED';
ALTER TYPE "LearningProjectStatus" ADD VALUE IF NOT EXISTS 'HIDDEN';

ALTER TABLE "learning_projects"
ADD COLUMN IF NOT EXISTS "submitted_at" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "reviewed_at" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "rejection_reason" TEXT,
ADD COLUMN IF NOT EXISTS "changes_requested_reason" TEXT,
ADD COLUMN IF NOT EXISTS "hidden_at" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "hidden_by" TEXT,
ADD COLUMN IF NOT EXISTS "hidden_reason" TEXT,
ADD COLUMN IF NOT EXISTS "archived_at" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "archived_by" TEXT,
ADD COLUMN IF NOT EXISTS "archived_reason" TEXT;
