-- ReservationStatus: NO_SHOW, FULFILLMENT_FAILED, AWAITING_RESOLUTION
ALTER TYPE "ReservationStatus" ADD VALUE IF NOT EXISTS 'NO_SHOW';
ALTER TYPE "ReservationStatus" ADD VALUE IF NOT EXISTS 'FULFILLMENT_FAILED';
ALTER TYPE "ReservationStatus" ADD VALUE IF NOT EXISTS 'AWAITING_RESOLUTION';

-- DeliveryStatus: DRIVER_NO_SHOW, LEARNER_NO_SHOW, AWAITING_RESOLUTION
ALTER TYPE "DeliveryStatus" ADD VALUE IF NOT EXISTS 'DRIVER_NO_SHOW';
ALTER TYPE "DeliveryStatus" ADD VALUE IF NOT EXISTS 'LEARNER_NO_SHOW';
ALTER TYPE "DeliveryStatus" ADD VALUE IF NOT EXISTS 'AWAITING_RESOLUTION';
